spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.21.149:3306/examination?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
  redis:
    cluster:
      nodes: 192.168.241.142:6379,
        192.168.241.139:6379,
        192.168.241.102:6379,
        192.168.241.103:6379,
        192.168.241.104:6379,
        192.168.241.105:6379,
        192.168.241.107:6379
      max-redirects: 3
      timeout: 5000
    jedis:
      pool:
        max-active: 10
        min-idle: 1
        max-wait: -1ms
        max-idle: 8
server:
  port: 8881
mybatis:
  mapper-locations: classpath:mybatis-mapper/*.xml
  type-aliases-package: com.haitun.haituntools.model
logging:
  file:
  path:
  config: classpath:logback-boot.xml
  level:
    org.springframework.web: DEBUG
    com.haitun : debug